on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      EXPIRES_SECONDS: 172800 # 2日間
      RESUME_PDF: 職務経歴書.pdf
      PERSONAL_HISTORY_PDF: 履歴書.pdf
      GO_VERSION: 1.19
      TZ: Asia/Tokyo
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install aws-cli
        run: |
          if ! which aws > /dev/null; then
            apt-get update && apt-get install -y curl unzip sudo make
            curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" \
              -o "awscliv2.zip" \
              && unzip awscliv2.zip \
              && sudo ./aws/install
          fi

      - name: Install wkhtmltopdf
        run: sudo apt-get install -y wkhtmltopdf

      - name: Install soffice
        run: |
          sudo apt-get install -y \
            libreoffice \
            libreoffice-l10n-ja \
            fonts-noto-cjk

      - name: Install pdftk
        run: |
          sudo apt-get install -y pdftk-java
          sudo ln -s /usr/bin/pdftk-java /usr/bin/pdftk

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup AWS Configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Build Generate Resume
        run: make all

      - name: Execute General Resume
        run: ./generate_resume config=config.json
        env:
          GOOGLE_SECRET_CREDENTIALS: ${{ secrets.GOOGLE_SECRET_CREDENTIALS }}

      - name: Remove PDF pages
        run: |
          pdftk-java ./outputs/$RESUME_PDF cat 1 output ./outputs/tmp_$RESUME_PDF
          mv -f ./outputs/tmp_$RESUME_PDF ./outputs/$RESUME_PDF

      - name: Upload Resume To S3
        run: aws s3 cp ./outputs/$RESUME_PDF s3://${{secrets.AWS_S3_BUCKET_DATA_STORE}}/

      - name: Send Signed URL Of Resume To Discord
        run: |
          signed_url=(`aws s3 presign s3://${{secrets.AWS_S3_BUCKET_DATA_STORE}}/$RESUME_PDF --expires-in $EXPIRES_SECONDS`)
          expires_date=(`date -d "+${EXPIRES_SECONDS} seconds" "+%Y-%m-%d"`)

          curl -X POST -H "Content-Type: application/json" -d "
          {
              \"content\": \"$RESUME_PDF:\n$signed_url\n有効期限:$expires_date\"
          }
          " ${{secrets.DISCORD_WEBHOOK_URL}}

      - name: Upload Personal History To S3
        run: aws s3 cp ./outputs/$PERSONAL_HISTORY_PDF s3://${{secrets.AWS_S3_BUCKET_DATA_STORE}}/

      - name: Send Signed URL Of Personal History To Discord
        run: |
          signed_url=(`aws s3 presign s3://${{secrets.AWS_S3_BUCKET_DATA_STORE}}/$PERSONAL_HISTORY_PDF --expires-in $EXPIRES_SECONDS`)
          expires_date=(`date -d "+${EXPIRES_SECONDS} seconds" "+%Y-%m-%d"`)

          curl -X POST -H "Content-Type: application/json" -d "
          {
              \"content\": \"$PERSONAL_HISTORY_PDF:\n$signed_url\n有効期限:$expires_date\"
          }
          " ${{secrets.DISCORD_WEBHOOK_URL}}
